const $=id=>document.getElementById(id),D=window.LOCAL_MAP_DATA,map=L.map('map',{zoomControl:true}).setView([-18.7,32.3],7);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);
const layers={centres:L.layerGroup().addTo(map),rail:L.layerGroup().addTo(map),boundary:L.layerGroup().addTo(map)};
L.rectangle([[-20.55,31.1],[-17,33.35]],{color:'#1f5b4a',weight:2,fill:false,dashArray:'6 5'}).addTo(layers.boundary);
L.geoJSON(D.businessCentres,{pointToLayer:(_,p)=>L.circleMarker(p,{radius:4,color:'#542f8b',fillColor:'#8f65c9',fillOpacity:.9,weight:1}),onEachFeature:(f,l)=>l.bindPopup(`Business centre<br>${f.geometry.coordinates[1].toFixed(4)}, ${f.geometry.coordinates[0].toFixed(4)}`)}).addTo(layers.centres);
L.geoJSON(D.railNetwork,{style:{color:'#384454',weight:2,dashArray:'6 5'},onEachFeature:(_,l)=>l.bindPopup('Rail network')}).addTo(layers.rail);
const setStatus=(t,e=false)=>{const x=$('status');x.textContent=t;x.className='status '+(e?'error':'')};
function counts(){$('centres-count').textContent=D.businessCentres.features.length;$('rail-count').textContent=D.railNetwork.features.length;$('stat-centres').textContent=D.businessCentres.features.length;$('stat-rail').textContent=D.railNetwork.features.length}
function pos(x){if(x.lat)return[x.lat,x.lon];if(x.center)return[x.center.lat,x.center.lon];if(x.geometry?.length){const a=x.geometry;return[a.reduce((s,p)=>s+p.lat,0)/a.length,a.reduce((s,p)=>s+p.lon,0)/a.length]}return null}
async function online(){setStatus('Loading OpenStreetMap schools and roads…');try{const q='[out:json][timeout:90];(nwr[amenity=school](-20.55,31.1,-17,33.35);way[highway~"^(primary|secondary|tertiary)$"](-20.55,31.1,-17,33.35););out body geom;',d=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:q}).then(r=>r.json());layers.schools.clearLayers();layers.roads.clearLayers();const s=d.elements.filter(x=>x.tags?.amenity==='school').map(pos).filter(Boolean);s.forEach(p=>L.circleMarker(p,{radius:5,color:'#fff',weight:1.5,fillColor:'#43aa75',fillOpacity:1}).bindPopup('Mapped school').addTo(layers.schools));const r=d.elements.filter(x=>x.tags?.highway&&x.geometry);r.forEach(x=>L.polyline(x.geometry.map(p=>[p.lat,p.lon]),{color:'#e26d3d',weight:2.5}).addTo(layers.roads));counts(s.length,r.length);setStatus('Online schools and roads loaded')}catch(e){setStatus('Local business centres and rail are ready',true)}}
Object.entries({'centres-toggle':'centres','rail-toggle':'rail','boundary-toggle':'boundary'}).forEach(([id,key])=>$(id).onchange=e=>e.target.checked?map.addLayer(layers[key]):map.removeLayer(layers[key]));counts();setStatus('Business centres and railway lines ready');
